apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop #if namespace is not mentioned then pod/deployment will excecute or run in default namespace
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  replicas: 1
  # replica details
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database

    # create pod & details
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database

    # container details
    spec:
      containers:
        - name: redis
          image: redis:7.0

---
# create services
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379 # service port
    targetPort: 6379 # container port